name: RL
channels:
- defaults
- pytorch
dependencies:
- python=3.6
- matplotlib
- pandas
- scipy
- jupyter
- jupyterlab
- scikit-learn
- pytorch-cpu
- torchvision-cpu
- pip:
  - gym
  - Pillow
  - gym[atari]